version: '1.0.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./LittleSteve/LittleSteve.csproj
build:
    project: LittleSteve.sln
    verbosity: minimal
test: off  
artifacts:
- path: '\LittleSteve\bin\Release\netcoreapp2.0\publish'
  name: 'LittleSteve.{version}'
deploy: off
