version: '1.0.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./LittleSteve/LittleSteve.csproj
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish -c Release
test: off  
artifacts:
- path: './LittleSteve/bin/Release/netcoreapp2.0/publish'
  name: 'LittleSteve.{version}'
deploy: off
